# conda environment description file for gha-workflows repo
#
# Create a conda environment for running gh and the utilities in this repo with:
#
#   $ conda env create -f envs/environment-dev.yaml
#   $ conda activate gha-workflows
#
# See the envs/requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: gha-workflows

channels:
  - conda-forge
  - nodefaults

dependencies:
  - gh
  - python=3.11
  - pyyaml
  - rich

  # For code style & repo QA
  - black
  - pre-commit
