# Reusable workflow to automatically add current milestone to issues and PRs

name: auto-milestone-issue-pr

on:
  workflow_call:

jobs:
  add_milestone:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: benelan/milestone-action@ae503769af66e741a9d7f76052058e1c3054fd7e
        with:
          # If true, add the milestone with the farthest due date. By default,
          # the action adds the current milestone (the closest due date).
          farthest: false

          # If true, overwrite existing milestones on issues and pull requests.
          # By default, the action exits if a milestone has already been added.
          overwrite: false

          # If true, add the only open milestone in a repo, even if there is no
          # due date. By default, milestones with no due date are ignored.
          single: false
