# Reusable workflow to auto-assign issues & PRs to Doug

name: auto-assign

on:
  workflow_call:

jobs:
  assign:
    name: Auto-assign to Doug
    runs-on: 'ubuntu-latest'
    steps:
      # Ignore the zizmor excessive-permissions warning because this is in a reusable workflow
      # and the permissions required to run the script depend on the context of the caller workflow
      - uses: actions/github-script@v9  # zizmor: ignore[unpinned-uses, excessive-permissions]
        with:
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [ 'douglatornell' ]
            })
