# Reusable workflow to run Sphinx linkcheck on docs via Pixi

name: pixi-sphinx-linkcheck

on:
  workflow_call:

jobs:
  sphinx-linkcheck:
    name: Sphinx linkcheck via Pixi
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7  # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false  # Required to avoid exposing secrets to the linkcheck process in forked PRs

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11
        with:
          cache: true

      - name: linkcheck docs
        # Ignore the zizmor excessive-permissions warning because this is in a reusable workflow
        # and the permissions required to run the command depend on the context of the caller workflow
        run: pixi run linkcheck  # zizmor: ignore[excessive-permissions]
