# Reusable workflow to do repo checkout and run pytest w/ coverage via Pixi,
# then upload coverage report to Codecov, and send job status notification to Slack

name: pixi-pytest-with-coverage

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  pytest-with-coverage:
    name: pytest with coverage in ${{ inputs.environment }} environment
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7  # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false  # Required to avoid exposing secrets to pytest run in forked PRs

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11
        with:
          cache: true
          environments: ${{ inputs.environment }}

      - name: Run pytest-with-coverage
        run: pixi run -e ${INPUTS_ENVIRONMENT} pytest --cov=$GITHUB_WORKSPACE --cov-report=xml
        env:
          INPUTS_ENVIRONMENT: ${{ inputs.environment }}

      - name: Upload coverage report to Codecov
        # Ignore the zizmor excessive-permissions warning because this is in a reusable workflow
        # and the permissions required to run the action depend on the context of the caller workflow
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # zizmor: ignore[excessive-permissions]
        with:
          files: ./coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
