# Reusable workflow to do repo checkout and run pytest w/ coverage via Pixi,
# then upload coverage report to Codecov, and send job status notification to Slack

name: pixi-pytest-with-coverage

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  pytest-with-coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0
        with:
          cache: true
          environments: ${{ inputs.environment }}

      - name: Run pytest-with-coverage
        run: pixi run -e ${{ inputs.environment }} pytest --cov=$GITHUB_WORKSPACE --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          files: ./coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
