# Reusable workflow to do repo checkout, build env, run pytest w/ coverage,
# upload coverage report to Codecov, and send job status notification to Slack

name: pytest-with-coverage

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      conda-env-file:
        required: true
        type: string
      conda-env-name:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  pytest-with-coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@617811f69075e3fd3ae68ca64220ad065877f246
        with:
           environment-file: ${{ inputs.conda-env-file }}
           environment-name: ${{ inputs.conda-env-name }}
           # environment caching does not play nicely with --editable installed packages
           cache-environment: false
           cache-downloads: true
           # persist downloads cache for 1 day
           cache-downloads-key: downloads-${{ steps.date.outputs.date }}
           create-args: >-
             python=${{ inputs.python-version }}

      - name: pytest package with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=$GITHUB_WORKSPACE --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          file: ./coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
