# Reusable workflow to run Sphinx linkcheck on docs

name: sphinx-linkcheck

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      conda-env-file:
        required: true
        type: string
      conda-env-name:
        required: true
        type: string
      docs-dir:
        default: docs
        required: false
        type: string

jobs:
  sphinx-linkcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@068f1ab4b37ed9b3d9f73da7db90a0cda0a48d29
        with:
           environment-file: ${{ inputs.conda-env-file }}
           environment-name: ${{ inputs.conda-env-name }}
           # environment caching does not play nicely with --editable installed packages
           cache-environment: false
           cache-downloads: true
           # persist downloads cache for 1 day
           cache-downloads-key: downloads-${{ steps.date.outputs.date }}
           create-args: >-
             python=${{ inputs.python-version }}

      - name: linkcheck docs
        shell: bash -l {0}
        working-directory: ${{ inputs.docs-dir }}
        run: |
          make linkcheck
